### PR TITLE
Bump version number in cmake.

### PR DESCRIPTION
**Pull request by dholladay00**
## PR Summary
@Yurlungur @rbberger creating a release version from the printf stuff.

## PR Checklist

- [x] Any changes to code are appropriately documented.
- [x] Code is formatted.
- [x] Install test passes.
- [x] Docs build.
- [x] If preparing for a new release, update the version in cmake.

### CODE REVIEW

**Comment by dholladay00** [comment]
@rbberger will this trigger Richard's Robots 🤖 ®️ ™️ ?!

**Comment by rbberger** [comment]
> @rbberger will this trigger Richard's Robots 🤖 ®️ ™️ ?!

:robot: Beep Beep Beep. No changes in `spack-repo/packages` found. Going back to sleep.

**Comment by rbberger** [comment]
@dholladay00 right now this only happens after the release, since that's when you have the release commit to add for the spackage.

**Review by Yurlungur — APPROVED** [review]

**Comment by Yurlungur** [comment]
I will click the button and then trigger a new release. Be prepared for robots.

**Pull request merged**
