### PR TITLE
CI Update

### PR DESCRIPTION
**Pull request by rbberger**
## PR Summary

- Upgrades common CI parts, adds ATS2 builds
- Adds reporting to LANL internal CDash
- Fixes some CMake issues

## PR Checklist

- [ ] Any changes to code are appropriately documented.
- [ ] Code is formatted.
- [ ] Install test passes.
- [ ] Docs build.
- [ ] If preparing for a new release, update the version in cmake.

### CODE REVIEW

**Comment by Yurlungur** [comment]
@rbberger since the cmake seems to be failing I assume this is WIP?

**Comment by Yurlungur** [comment]
> @rbberger since the cmake seems to be failing I assume this is WIP?

ah nevermind. I see you fixed it.

**Comment by Yurlungur** [comment]
Let me know when you're ready to merge.

**Comment by rbberger** [comment]
@Yurlungur This is ready.

**Pull request merged**
