### PR TITLE
Add config_summary to Ports-of-Call.

### PR DESCRIPTION
**Pull request by BrendanKKrueger**
## PR Summary

A recent addition to Singe.  Jonah said Ports-of-Call might find it useful, so putting together a demo so y'all can see if you like it or not.

@Yurlungur @dholladay00 @cmauney 

## PR Checklist

- [ ] Any changes to code are appropriately documented.
- [ ] Code is formatted.
- [ ] Install test passes.
- [ ] Docs build.
- [ ] If preparing for a new release, update the version in cmake.

### CODE REVIEW

**Comment by BrendanKKrueger** [comment]
By the way, if you want to see how this looks for Singe as an example, Diego has a screenshot [here](https://re-git.lanl.gov/xcap/ec/singe/-/merge_requests/438#note_974126).

**Review by Yurlungur — APPROVED** [review]
THis is nice. I think @mauneyc-LANL at some point tried to implement something like this but maybe not in ports.

**Review by mauneyc-LANL — APPROVED** [review]

**Comment by BrendanKKrueger** [comment]
Let me know if these are the right options to display for Ports-of-Call, because I wasn't sure.

**Comment by Yurlungur** [comment]
It seems totally reasonable to me.

**Pull request merged**
