### PR TITLE
spack: own py-sphinx-multiversion no longer needed

### PR DESCRIPTION
**Pull request by rbberger**
## PR Summary

Since our testing Spack upstream is now Spack v0.18+ this spackage is no longer needed

## PR Checklist

- [ ] Any changes to code are appropriately documented.
- [ ] Code is formatted.
- [ ] Install test passes.
- [ ] Docs build.

### CODE REVIEW

**Review by Yurlungur — APPROVED** [review]
Looks like "deploy" is failing. Probably because it's a fork. I approve. Assume this is because `py-sphinx-multiversion` is available upstream?

**Comment by Yurlungur** [comment]
Oh also please add changelog. ;)

**Comment by rbberger** [comment]
> Oh also please add changelog. ;)

What does this mean in this repository? I don't see a changelog.

**Comment by Yurlungur** [comment]
> > Oh also please add changelog. ;)
> 
> What does this mean in this repository? I don't see a changelog.

Oh oops this is `ports-of-call`, which doesn't have a changelog. Nevermind on that. :)

**Pull request merged**
